# Generated by Django 5.2.4 on 2025-07-30 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Задача')),
                ('term', models.DateTimeField(blank=True, null=True, verbose_name='Срок')),
                ('creating_date', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Отредактировно')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В исполнении'), ('done', 'Выполнено')], verbose_name='Статус')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
